{
 "title": "Skyfox Backend - AMP",
 "description": "Data fetched from AWS Hosted Backend on ECS through AWS Managed Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "API Traffic by Endpoint Group",
   "type": "timeseries",
   "description": "Shows the number of API requests per business function (feature group), making it easy to spot which parts of the system are most used.",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint_group) (increase(skyfox_http_requests_total{endpoint_group!=\"other\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency (P95) by Endpoint Group",
   "type": "stat",
   "description": "Displays the 95th percentile response time for each business function, highlighting the slowest parts of the API pipeline for proactive tuning.",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(skyfox_http_request_duration_seconds_bucket{endpoint_group!=\"other\"}[5m])) by (le, endpoint_group))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unrecognized Requests (API Noise)",
   "type": "timeseries",
   "description": "Shows API “noise” or suspicious traffic—requests that don’t match any defined business route. Useful for security observability and bot detection.",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum (increase(skyfox_http_requests_total{endpoint_group=\"other\"}[5m]))by (le, endpoint_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Status Code Overview (BL)",
   "type": "piechart",
   "description": "Breakdown of responses by HTTP status code (e.g., 200, 403, 500) across all business functions—shows API health and security effectiveness at a glance.",
   "gridPos": { "h": 14, "w": 4, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (increase(skyfox_http_requests_total{endpoint_group!=\"other\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Malicious Requests Not Blocked",
   "type": "stat",
   "description": "Visualizes how many requests per group were blocked due to failed authentication/authorization, demonstrating security defenses in action.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint_group) (increase(skyfox_http_requests_total{status_code!=\"403\",endpoint_group=\"other\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Malicious Requests Blocked",
   "type": "stat",
   "description": "Visualizes how many unauthorized requests were blocked.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint_group) (increase(skyfox_http_requests_total{status_code=\"403\",endpoint_group=\"other\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}