# ADOT Configuration for SkyFox Backend Monitoring
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'skyfox-backend'
          scrape_interval: 30s
          metrics_path: /metrics
          static_configs:
            - targets: ["backend:8080"]
          
          relabel_configs:
            - target_label: instance
              replacement: "backend-sidecar-${deployment_id}"
            - target_label: service_name
              replacement: "skyfox-backend"
            - target_label: cluster_name  
              replacement: "${ecs_cluster_name}"

processors:
  batch:
    send_batch_size: 100  
    timeout: 30s     
    send_batch_max_size: 200

  memory_limiter:
    check_interval: 10s
    limit_mib: 200

exporters:
  # AWS Managed Prometheus Exporter
  prometheusremotewrite:
    endpoint: "$${AMP_ENDPOINT}/workspaces/$${AMP_WORKSPACE_ID}/api/v1/remote_write"
    auth:
      authenticator: sigv4auth
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 120s

extensions:
  sigv4auth:
    region: ap-south-1

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite]
  
  telemetry:
    logs:
      level: "info"